import type { Metadata } from "next";
import { ProtectedLayout } from "./admin/_components/ProtectedLayout";

export const metadata: Metadata = {
  title: "Project IT",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProtectedLayout>
      {children}
    </ProtectedLayout>
  );
}
